title: Welcome to Antarctica
hero_image: images/banner.png
description: Use HTML, CSS, and JavaScript to make a great website
version: 1
copyedit: false
last_tested: '2026-03-16'
listed: false
pdf: false
landing: true
steps:
  - title: Change the font
  - title: Create a navigation bar
    completion:
      - engaged
  - title: Style the navigation bar
  - title: Add hero images
  - title: Different hero images
  - title: Arrange facts with grids
  - title: Add hover animations
  - title: Create a wildlife grid
  - title: Create a climate grid
    completion:
      - internal
  - title: Make the menu work on small screens
    completion:
      - external
