title: Welcome to Antarctica
hero_image: images/banner.png
description: Use HTML, CSS, and JavaScript to make a great website
version: 5
copyedit: false
last_tested: '2026-03-16'
listed: false
pdf: false
steps:
- title: Step 1
- title: Step 2
  completion:
  - engaged
- title: Step 3
- title: Step 4
- title: Step 5
- title: Step 6
- title: Step 7
- title: Step 8
- title: Step 9
- title: Step 10
  completion:
  - internal
- title: Step 11
  completion:
  - external
